---
title: "Análisis de dataset basado en IHDP"
author: "Constanza de Galvagni"
date: '2025'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE  
)
```

```{r warning = FALSE}
library(ggplot2)
library(patchwork)
library(ggdensity)
library(ggdist)
library(dplyr)
library(cowplot)
```

Creamos gráficos de ejemplo para ver los valores que toman las medias de las normales que usamos para generar las superficies A y B.

```{r}
pdf("../figuras/means_superficies.pdf", width = 8, height = 6)
x_grilla <- seq(-5,5,0.01)
y0_A = x_grilla
y1_A = x_grilla+4
plot(y0_A,type="l", xlab = "Grilla de valores", ylab = "Media")
lines(y1_A, col="red")
legend("bottomright", legend = c("mean(Y0), supA", "mean(Y1), supA"), col = c("black", "red"), pch = 18)

x_grilla <- seq(-5,5,0.01)
w = 0.5
beta=1
y0 = exp((x_grilla+w)*beta)
y1 = x_grilla *beta 
plot(y0,type="l", xlab = "Grilla de valores", ylab = "Media")
lines(y1, col = "red")
legend("topleft", legend = c("mean(Y0), supB", "mean(Y1), supB"), col = c("black", "red"), pch = 18)

x_grilla <- seq(-5,5,0.01)
w = 0.5
beta=1
y0 = exp((x_grilla+w)*beta)
y1 = x_grilla *beta 
plot(log(y0),type="l", xlab = "Grilla de valores", ylab = "log(Media)")
lines(log(y1), col = "red")
legend("topleft", legend = c("log(mean(Y0)), supB", "log(mean(Y1)), supB"), col = c("black", "red"), pch = 18)

dev.off()
```

Leemos los datos que generamos en el archivo de experimentacion_hill para analizar la performance de los modelos bajo esos datos

```{r}
res_sup_A <- read.csv('resultados/results_sup_A.csv')
res_sup_B <- read.csv('resultados/results_sup_B.csv')

if (!dir.exists("../figuras/resultados_ihdp")) {
  dir.create("../figuras/resultados_ihdp")
}

```

```{r}
df_ate_vs_rmse_train_supA <- data.frame(
  ate_train = c(res_sup_A$BCF.ate_train, res_sup_A$CF.ate_train, res_sup_A$BART.ate_train),
  rmse_ate_train = c(res_sup_A$BCF.rmse_ate_train, res_sup_A$CF.rmse_ate_train, res_sup_A$BART.rmse_ate_train),
  modelo = factor(rep(c("BCF", "CF", "BART"), each = nrow(res_sup_A)))
)

df_ate_vs_rmse_train_supB <- data.frame(
  ate_train = c(res_sup_B$BCF.ate_train, res_sup_B$CF.ate_train, res_sup_B$BART.ate_train),
  rmse_ate_train = c(res_sup_B$BCF.rmse_ate_train, res_sup_B$CF.rmse_ate_train, res_sup_B$BART.rmse_ate_train),
  modelo = factor(rep(c("BCF", "CF", "BART"), each = nrow(res_sup_B)))
)

df_ate_vs_rmse_test_supA <- data.frame(
  ate_test = c(res_sup_A$BCF.ate_test, res_sup_A$CF.ate_test, res_sup_A$BART.ate_test),
  rmse_ate_test = c(res_sup_A$BCF.rmse_ate_test, res_sup_A$CF.rmse_ate_test, res_sup_A$BART.rmse_ate_test),
  modelo = factor(rep(c("BCF", "CF", "BART"), each = nrow(res_sup_A)))
)

df_ate_vs_rmse_test_supB <- data.frame(
  ate_test = c(res_sup_B$BCF.ate_test, res_sup_B$CF.ate_test, res_sup_B$BART.ate_test),
  rmse_ate_test = c(res_sup_B$BCF.rmse_ate_test, res_sup_B$CF.rmse_ate_test, res_sup_B$BART.rmse_ate_test),
  modelo = factor(rep(c("BCF", "CF", "BART"), each = nrow(res_sup_B)))
)

ate_train_vs_rmse_sup_A <- ggplot(df_ate_vs_rmse_train_supA, aes(x = ate_train, y = rmse_ate_train)) +
  geom_density_2d_filled(contour_var = "ndensity") +
  facet_wrap(~modelo) +
  guides(fill = "none") +
  coord_cartesian(ylim = c(NA, quantile(df_ate_vs_rmse_train_supA$rmse_ate_train, 0.975)))+
  scale_fill_viridis_d(option = "magma") +
  geom_vline(xintercept = 4, linetype = "dashed", color = "white")+
  labs(
    title = expression(ATE[train] ~ "vs RMSE "~ (ATE[train])~" para sup. A"),
    x = expression(hat(ATE)[train]),
    y = "RMSE(ATE)"
  ) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 16),  # Título eje X
    axis.title.y = element_text(size = 16),  # Título eje Y
    axis.text.x = element_text(size = 12),   # Números en eje X
    axis.text.y = element_text(size = 12),
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
    strip.text = element_text(size = 16)
  ) 

ate_test_vs_rmse_sup_A <- ggplot(df_ate_vs_rmse_test_supA, aes(x = ate_test, y = rmse_ate_test)) +
  geom_density_2d_filled(contour_var = "ndensity") +
  facet_wrap(~modelo) +
  guides(fill = "none") +
  coord_cartesian(ylim = c(NA, quantile(df_ate_vs_rmse_test_supA$rmse_ate_test, 0.975))) + 
  scale_fill_viridis_d(option = "magma") +
  geom_vline(xintercept = 4, linetype = "dashed", color = "white")+
  labs(
    title = expression(ATE[test] ~ "vs RMSE "(ATE[test])~" para sup. A"),
    x = expression(hat(ATE)[test]),
    y = "RMSE(ATE)"
  ) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 16),  # Título eje X
    axis.title.y = element_text(size = 16),  # Título eje Y
    axis.text.x = element_text(size = 12),   # Números en eje X
    axis.text.y = element_text(size = 12),
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
    strip.text = element_text(size = 16)
  ) 

ate_train_vs_rmse_sup_A
ggsave("../figuras/resultados_ihdp/ate_train_vs_rmse_supA.pdf", units = "in", plot = ggdraw(ate_train_vs_rmse_sup_A))
ate_test_vs_rmse_sup_A
ggsave("../figuras/resultados_ihdp/ate_test_vs_rmse_supA.pdf", units = "in" , plot = ggdraw(ate_test_vs_rmse_sup_A))
```
```{r warning = FALSE}
ate_train_vs_rmse_sup_B <- ggplot(df_ate_vs_rmse_train_supB, aes(x = ate_train, y = rmse_ate_train)) +
  geom_density_2d_filled(contour_var = "ndensity") +
  geom_point(alpha = 0.3, size = 1, color = "white") + 
  facet_wrap(~modelo) +
  guides(fill = "none") +
  scale_fill_viridis_d(option = "magma") +
  labs(
    title = expression(ATE[train] ~ "vs RMSE "~ (ATE[train])~" para sup. B"),
    x = expression(hat(ate)[train]),
    y = "RMSE(ATE)"
  ) +
  theme_minimal()

ate_test_vs_rmse_sup_B <- ggplot(df_ate_vs_rmse_test_supB, aes(x = ate_test, y = rmse_ate_test)) +
  geom_density_2d_filled(contour_var = "ndensity") +
  geom_point(alpha = 0.3, size = 1, color = "white") + 
  facet_wrap(~modelo) +
  scale_fill_viridis_d(option = "magma") +
  labs(
    title = expression(ATE[test] ~ "vs RMSE "~ (ATE[test])~" para sup. B"),
    x = expression(hat(ATE)[test]),
    y = "RMSE(ATE)"
  ) +
  theme_minimal()

ate_train_vs_rmse_sup_B
ggsave("../figuras/resultados_ihdp/ate_train_vs_rmse_supB_original.pdf", units = "in" , plot = ggdraw(ate_train_vs_rmse_sup_B))
ate_test_vs_rmse_sup_B
ggsave("../figuras/resultados_ihdp/ate_test_vs_rmse_supB_original.pdf", units = "in" , plot = ggdraw(ate_test_vs_rmse_sup_B + guides(fill = "none")))
```

```{r}
ymax_rmse_ate_B = max(quantile(df_ate_vs_rmse_train_supB$ate_train,0.9), quantile(df_ate_vs_rmse_test_supB$ate_test,0.9))
xmin_rmse_ate_B = max(quantile(df_ate_vs_rmse_train_supB$ate_train, 0.05), quantile(df_ate_vs_rmse_test_supB$ate_test, 0.05))
xmax_rmse_ate_B = max(quantile(df_ate_vs_rmse_train_supB$ate_train, 0.95), quantile(df_ate_vs_rmse_test_supB$ate_test, 0.95))

ate_train_vs_rmse_sup_B <- ggplot(df_ate_vs_rmse_train_supB, aes(x = ate_train, y = rmse_ate_train)) +
  geom_density_2d_filled(contour_var = "ndensity") +
  facet_wrap(~modelo) +
  guides(fill = "none") +
  coord_cartesian(ylim = c(NA, ymax_rmse_ate_B), 
                xlim = c(xmin_rmse_ate_B,xmax_rmse_ate_B)) +  
  scale_fill_viridis_d(option = "magma") +
  geom_vline(xintercept = 4, linetype = "dashed", color = "white")+
  labs(
    title = expression(ATE[train] ~ "vs RMSE "~ (ATE[train])~" para sup. B"),
    x = expression(hat(ATE)[train]),
    y = "RMSE(ATE)"
  ) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 16),  # Título eje X
    axis.title.y = element_text(size = 16),  # Título eje Y
    axis.text.x = element_text(size = 12),   # Números en eje X
    axis.text.y = element_text(size = 12),
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
    strip.text = element_text(size = 16)
  ) 

ate_test_vs_rmse_sup_B <- ggplot(df_ate_vs_rmse_test_supB, aes(x = ate_test, y = rmse_ate_test)) +
  geom_density_2d_filled(contour_var = "ndensity") +
  facet_wrap(~modelo) +
  coord_cartesian(ylim = c(NA, ymax_rmse_ate_B), 
                xlim = c(xmin_rmse_ate_B,xmax_rmse_ate_B)) + 
  geom_vline(xintercept = 4, linetype = "dashed", color = "white")+
  scale_fill_viridis_d(option = "magma", name = NULL) +
  labs(
    title = expression(ATE[test] ~ "vs RMSE "~ (ATE[test])~" para sup. B"),
    x = expression(hat(ATE)[test]),
    y = "RMSE(ATE)"
  ) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(direction = "horizontal", title.position = "top", title.hjust = 0.5)) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 16),  # Título eje X
    axis.title.y = element_text(size = 16),  # Título eje Y
    axis.text.x = element_text(size = 12),   # Números en eje X
    axis.text.y = element_text(size = 12),
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
    strip.text = element_text(size = 16)
  ) 

legend_ates <- get_legend(ate_test_vs_rmse_sup_B)
ggsave("../figuras/resultados_ihdp/leyenda_rmse_vs_tau.pdf", units = "in" , plot = ggdraw(legend_ates), width = 6, height = 1.5)

ate_train_vs_rmse_sup_B
ggsave("../figuras/resultados_ihdp/ate_train_vs_rmse_supB.pdf", units = "in" , plot = ggdraw(ate_train_vs_rmse_sup_B))
ate_test_vs_rmse_sup_B + guides(fill = "none")
ggsave("../figuras/resultados_ihdp/ate_test_vs_rmse_supB.pdf", units = "in" , plot = ggdraw(ate_test_vs_rmse_sup_B + guides(fill = "none")))
```
```{r}
df_cate_rmse_supA <- data.frame(
  rmse = c(
    res_sup_A$BCF.rmse_cate_train, res_sup_A$CF.rmse_cate_train, res_sup_A$BART.rmse_cate_train,
    res_sup_A$BCF.rmse_cate_test,  res_sup_A$CF.rmse_cate_test,  res_sup_A$BART.rmse_cate_test
  ),
  modelo = factor(rep(c("BCF", "CF", "BART"), each = 2 * nrow(res_sup_A))),
  split = factor(rep(c("train", "test"), each = nrow(res_sup_A), times = 3))
)

plot_rmse_cate_supA <- ggplot(df_cate_rmse_supA, aes(x = modelo, y = rmse, fill = split)) +
  geom_boxplot(position = position_dodge(width = 0.8), alpha = 0.7) +
  labs(
    title = "Comparación de RMSE(CATE) entre Train y Test - Sup. A",
    x = "Modelo",
    y = "RMSE(CATE)",
    fill = "Split"
  ) +
  scale_fill_viridis_d(option = "plasma") +
  theme_minimal()+
     theme(
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 14),
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 13)
  )
plot_rmse_cate_supA
ggsave("../figuras/resultados_ihdp/rmse_cate_supA.pdf", units = "in" , plot = ggdraw(plot_rmse_cate_supA))
```
```{r}
df_cate_rmse_supB <- data.frame(
  rmse = c(
    res_sup_B$BCF.rmse_cate_train, res_sup_B$CF.rmse_cate_train, res_sup_B$BART.rmse_cate_train,
    res_sup_B$BCF.rmse_cate_test,  res_sup_B$CF.rmse_cate_test,  res_sup_B$BART.rmse_cate_test
  ),
  modelo = factor(rep(c("BCF", "CF", "BART"), each = 2 * nrow(res_sup_B))),
  split = factor(rep(c("train", "test"), each = nrow(res_sup_B), times = 3))
)

rmse_cate_supB_outliers <- ggplot(df_cate_rmse_supB, aes(x = modelo, y = rmse, fill = split)) +
  geom_boxplot(position = position_dodge(width = 0.8), alpha = 0.7) +
  labs(
    title = "Comparación de RMSE(CATE) entre Train y Test - Sup. B",
    x = "Modelo",
    y = "RMSE(CATE)",
    fill = "Split"
  ) +
  scale_fill_viridis_d(option = "plasma") +
  theme_minimal()+
   theme(
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 14),
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 13)
  )
rmse_cate_supB_outliers
ggsave("../figuras/resultados_ihdp/rmse_cate_supB_outliers.pdf", units = "in" , plot = ggdraw(rmse_cate_supB_outliers))
```
```{r}
ymax_boxplots_cate_B <- max(quantile(df_cate_rmse_supB$rmse, 0.95))

rmse_cate_supB <- ggplot(df_cate_rmse_supB, aes(x = modelo, y = rmse, fill = split)) +
  coord_cartesian(ylim = c(NA,quantile(df_cate_rmse_supB$rmse, 0.95))) +
  geom_boxplot(position = position_dodge(width = 0.8), alpha = 0.7) +
  labs(
    title = "Comparación de RMSE(CATE) entre Train y Test - Sup. B",
    x = "Modelo",
    y = "RMSE(CATE)",
    fill = "Split"
  ) +
  scale_fill_viridis_d(option = "plasma") +
  theme_minimal() +
   theme(
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 14),
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 13)
  )
rmse_cate_supB
ggsave("../figuras/resultados_ihdp/rmse_cate_supB.pdf", units = "in" , plot = ggdraw(rmse_cate_supB))
```
```{r}
df_rmse_cate_su <- data.frame(
  valor = c(
    res_sup_A$BART.tam_medio_ic_train,
    res_sup_A$BCF.tam_medio_ic_train,
    res_sup_A$CF.tam_medio_ic_train,
    res_sup_A$BART.tam_medio_ic_test,
    res_sup_A$BCF.tam_medio_ic_test,
    res_sup_A$CF.tam_medio_ic_test
  ),
  modelo = rep(c("BART", "BCF", "CF"), each = 500 * 2),
  conjunto = rep(c("train", "test"), each = 500, times = 3)
)

df_tam_ic_supB <- data.frame(
  valor = c(
    res_sup_B$BART.tam_medio_ic_train,
    res_sup_B$BCF.tam_medio_ic_train,
    res_sup_B$CF.tam_medio_ic_train,
    res_sup_B$BART.tam_medio_ic_test,
    res_sup_B$BCF.tam_medio_ic_test,
    res_sup_B$CF.tam_medio_ic_test
  ),
  modelo = rep(c("BART", "BCF", "CF"), each = 500 * 2),
  conjunto = rep(c("train", "test"), each = 500, times = 3)
)
```

```{r}
df_tam_ic_supA <- data.frame(
  valor = c(
    res_sup_A$BART.tam_medio_ic_train,
    res_sup_A$BCF.tam_medio_ic_train,
    res_sup_A$CF.tam_medio_ic_train,
    res_sup_A$BART.tam_medio_ic_test,
    res_sup_A$BCF.tam_medio_ic_test,
    res_sup_A$CF.tam_medio_ic_test
  ),
  modelo = rep(c("BART", "BCF", "CF"), each = 500 * 2),
  conjunto = rep(c("train", "test"), each = 500, times = 3)
)

df_tam_ic_supB <- data.frame(
  valor = c(
    res_sup_B$BART.tam_medio_ic_train,
    res_sup_B$BCF.tam_medio_ic_train,
    res_sup_B$CF.tam_medio_ic_train,
    res_sup_B$BART.tam_medio_ic_test,
    res_sup_B$BCF.tam_medio_ic_test,
    res_sup_B$CF.tam_medio_ic_test
  ),
  modelo = rep(c("BART", "BCF", "CF"), each = 500 * 2),
  conjunto = rep(c("train", "test"), each = 500, times = 3)
)


library(ggridges)
library(forcats)


tam_ics_supA <- ggplot(df_tam_ic_supA, aes(x = modelo, y = valor, fill = conjunto)) +
  geom_violin(alpha = 0.4, color = NA, position = position_dodge(width = 0.9), scale = "width") +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9),
              size = 0.8, alpha = 0.4, shape = 21, stroke = 0.2, color = "black") +
  labs(
    x = "Modelo",
    y = "Tamaño medio del intervalo de confianza del ATE",
    fill = "Conjunto"
  ) +
  scale_fill_viridis_d(option = "plasma") +
  theme_minimal(base_size = 14) +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14)
  )

tam_ics_supB <- ggplot(df_tam_ic_supB, aes(x = modelo, y = valor, fill = conjunto)) +
  geom_violin(alpha = 0.4, color = NA, position = position_dodge(width = 0.9), scale = "width") +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9),
              size = 0.8, alpha = 0.4, shape = 21, stroke = 0.2, color = "black") +
  labs(
    x = "Modelo",
    y = "Tamaño medio del intervalo de confianza del ATE",
    fill = "Conjunto"
  ) +
  scale_fill_viridis_d(option = "plasma", name = "Conjunto", guide = guide_legend()) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14)
  )

tam_ics_supB_sinoutliers <- ggplot(df_tam_ic_supB, aes(x = modelo, y = valor, fill = conjunto)) +
  geom_violin(alpha = 0.4, color = NA, position = position_dodge(width = 0.9), scale = "width") +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9),
              size = 0.8, alpha = 0.4, shape = 21, stroke = 0.2, color = "black") +
  coord_cartesian(ylim = c(NA, quantile(df_tam_ic_supB$valor, 0.95))) +
  labs(
    x = "Modelo",
    y = "Tamaño medio del intervalo de confianza del ATE",
    fill = "Conjunto"
  ) +
  scale_fill_viridis_d(option = "plasma", name = "Conjunto", guide = guide_legend()) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14)
  )


tam_ics_supA
ggsave("../figuras/resultados_ihdp/tam_ics_supA.pdf", units = "in" , plot = ggdraw(tam_ics_supA))
tam_ics_supB
ggsave("../figuras/resultados_ihdp/tam_ics_supB.pdf", units = "in" , plot = ggdraw(tam_ics_supB))
tam_ics_supB_sinoutliers
ggsave("../figuras/resultados_ihdp/tam_ics_supB_sinoutliers.pdf", units = "in" , plot = ggdraw(tam_ics_supB_sinoutliers))

```
```{r}
df_cov_ate_supA <- data.frame(
  coverage = c(
    res_sup_A$BART.coverage_ate_train,
    res_sup_A$BART.coverage_ate_test,
    res_sup_A$BCF.coverage_ate_train,
    res_sup_A$BCF.coverage_ate_test,
    res_sup_A$CF.coverage_ate_train,
    res_sup_A$CF.coverage_ate_test
  ),
  modelo = factor(rep(c("BART", "BART", "BCF", "BCF", "CF", "CF"),
                      each = nrow(res_sup_A))),
  conjunto = rep(c("train", "test"), times = 3 * nrow(res_sup_A) / 2)
)

df_cov_ate_supB <- data.frame(
  coverage = c(
    res_sup_B$BART.coverage_ate_train,
    res_sup_B$BART.coverage_ate_test,
    res_sup_B$BCF.coverage_ate_train,
    res_sup_B$BCF.coverage_ate_test,
    res_sup_B$CF.coverage_ate_train,
    res_sup_B$CF.coverage_ate_test
  ),
  modelo = factor(rep(c("BART", "BART", "BCF", "BCF", "CF", "CF"),
                      each = nrow(res_sup_B))),
  conjunto = rep(c("train", "test"), times = 3 * nrow(res_sup_B) / 2)
)
library(ggbeeswarm)

cov_ate_sup_A <- ggplot(df_cov_ate_supA, aes(x = modelo, y = coverage, fill = conjunto)) +
  geom_violin(position = position_dodge(width = 0.9), alpha = 0.4, width = 0.9, color = NA) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9),
              size = 0.8, alpha = 0.4, shape = 21, stroke = 0.2, color = "black") +
  scale_fill_viridis_d(option = "plasma") +
  scale_color_viridis_d(option = "plasma") +
  labs(
    title = "Coverage del ATE - Sup. A",
    x = "Modelo",
    y = "Coverage",
    fill = "Conjunto"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "bottom",
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14)
  ) +
  guides(fill = guide_legend(direction = "horizontal", title.position = "top", title.hjust = 0.5))

cov_ate_sup_B <- ggplot(df_cov_ate_supB, aes(x = modelo, y = coverage, fill = conjunto)) +
  geom_violin(position = position_dodge(width = 0.9), alpha = 0.4, width = 0.9, color = NA) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9),
              size = 0.8, alpha = 0.4, shape = 21, stroke = 0.2, color = "black") +
  scale_fill_viridis_d(option = "plasma") +
  scale_color_viridis_d(option = "plasma") +
  labs(
    title = "Coverage del ATE - Sup. B",
    x = "Modelo",
    y = "Coverage",
    fill = "Conjunto"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "bottom",
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14)
  ) +
  guides(fill = guide_legend(direction = "horizontal", title.position = "top", title.hjust = 0.5))

cov_ate_sup_A
cov_ate_sup_B

ggsave("../figuras/resultados_ihdp/cov_ate_supA.pdf", units = "in" , plot = ggdraw(cov_ate_sup_A))
ggsave("../figuras/resultados_ihdp/cov_ate_supB.pdf", units = "in" , plot = ggdraw(cov_ate_sup_B))
```
```{r}
df_cov_cate_supA <- data.frame(
  coverage = c(
    res_sup_A$BART.coverage_cate_train,
    res_sup_A$BART.coverage_cate_test,
    res_sup_A$BCF.coverage_cate_train,
    res_sup_A$BCF.coverage_cate_test,
    res_sup_A$CF.coverage_cate_train,
    res_sup_A$CF.coverage_cate_test
  ),
  modelo = factor(rep(c("BART", "BART", "BCF", "BCF", "CF", "CF"),
                      each = nrow(res_sup_A))),
  conjunto = rep(c("train", "test"), times = 3 * nrow(res_sup_A) / 2)
)


na_labels_cate_supA <- df_cov_cate_supA %>%
  group_by(modelo, conjunto) %>%
  summarise(prop_na = mean(is.na(coverage)), .groups = "drop") %>%
  mutate(label = paste0("NA: ", round(prop_na * 100, 1), "%"))

df_cov_cate_supB <- data.frame(
  coverage = c(
    res_sup_B$BART.coverage_cate_train,
    res_sup_B$BART.coverage_cate_test,
    res_sup_B$BCF.coverage_cate_train,
    res_sup_B$BCF.coverage_cate_test,
    res_sup_B$CF.coverage_cate_train,
    res_sup_B$CF.coverage_cate_test
  ),
  modelo = factor(rep(c("BART", "BART", "BCF", "BCF", "CF", "CF"),
                      each = nrow(res_sup_B))),
  conjunto = rep(c("train", "test"), times = 3 * nrow(res_sup_B) / 2)
)
na_labels_cate_supB <- df_cov_cate_supB %>%
  group_by(modelo, conjunto) %>%
  summarise(prop_na = mean(is.na(coverage)), .groups = "drop") %>%
  mutate(label = paste0("NA: ", round(prop_na * 100, 1), "%"))
library(ggbeeswarm)

cov_cate_supA <- ggplot(df_cov_cate_supA, aes(x = modelo, y = coverage, fill = conjunto)) +
  geom_violin(position = position_dodge(width = 0.9), alpha = 0.4, width = 0.9, color = NA) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9),
              size = 0.8, alpha = 0.4, shape = 21, stroke = 0.2, color = "black") +
  coord_cartesian(ylim=c(0,1.1)) +
  scale_fill_viridis_d(option = "plasma") +
  scale_color_viridis_d(option = "plasma") +
  labs(
    title = "Coverage del CATE - Sup. A",
    x = "Modelo",
    y = "Coverage",
    fill = "Conjunto"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "bottom",
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14)
  ) +
  geom_text(data = na_labels_cate_supA, 
            aes(x = modelo, y = 1.05, group = conjunto, label = label), 
            position = position_dodge(width = 0.9), 
            size = 3.5, vjust = 0) +
  guides(fill = guide_legend(direction = "horizontal", title.position = "top", title.hjust = 0.5))


cov_cate_supB <- ggplot(df_cov_cate_supB, aes(x = modelo, y = coverage, fill = conjunto)) +
  geom_violin(position = position_dodge(width = 0.9), alpha = 0.4, width = 0.9, color = NA) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9),
              size = 0.8, alpha = 0.4, shape = 21, stroke = 0.2, color = "black") +
  scale_fill_viridis_d(option = "plasma") +
  scale_color_viridis_d(option = "plasma") +
  labs(
    title = "Coverage del CATE - Sup. B",
    x = "Modelo",
    y = "Coverage",
    fill = "Conjunto"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "bottom",
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14)
  ) +
  geom_text(data = na_labels_cate_supB, 
            aes(x = modelo, y = 1.05, group = conjunto, label = label), 
            position = position_dodge(width = 0.9), 
            size = 3.5, vjust = 0) +
  guides(fill = guide_legend(direction = "horizontal", title.position = "top", title.hjust = 0.5))

cov_cate_supA
cov_cate_supB

ggsave("../figuras/resultados_ihdp/cov_cate_supA.pdf", units = "in" , plot = ggdraw(cov_cate_supA))
ggsave("../figuras/resultados_ihdp/cov_cate_supB.pdf", units = "in" , plot = ggdraw(cov_cate_supB))
```

```{r}
data_gelman_supA <- data.frame(
  dataset = rep(1:500, times = 2),
  conjunto = rep(c("Train", "Test"), each = 500),
  gelman = c(res_sup_A$BART.gelman_train, res_sup_A$BART.gelman_test)
)

data_gelman_supB <- data.frame(
  dataset = rep(1:500, times = 2),
  conjunto = rep(c("Train", "Test"), each = 500),
  gelman = c(res_sup_B$BART.gelman_train, res_sup_B$BART.gelman_test)
)

data_gelman_supA$superficie <- "sup.A"
data_gelman_supB$superficie <- "sup.B"

data_gelman_total <- rbind(data_gelman_supA, data_gelman_supB)
data_gelman_total$grupo <- interaction(data_gelman_total$conjunto, data_gelman_total$superficie, sep = "_")

colores <- c(
  "Train_sup.A" = "#FFD700",    
  "Test_sup.A" = "#9370DB",     
  "Train_sup.B" = "#00C853",    
  "Test_sup.B" = "#FF4081"     
)

gelman_bart <- ggplot(data_gelman_total, aes(x = gelman, fill = grupo, color = grupo)) +
  geom_density(alpha = 0.2, linewidth = 0.8) +
  scale_fill_manual(values = colores) +
  scale_color_manual(values = colores) +
  #geom_vline(xintercept = 1.5, linetype = "solid", color = "black") +
  labs(
    #title = "Distribución del estadístico Gelman-Rubin por conjunto y superficie",
    x = "Gelman-Rubin R̂",
    y = "Densidad",
    color = "Conjunto y superficie",
    fill = "Conjunto y superficie"
  ) +
  geom_vline(xintercept = 1.1, color = "blue", size = 0.8, linetype = "dashed")+
  theme_minimal(base_size = 14)+
  theme(legend.position = c(0.6, 0.6))
gelman_bart
ggsave("../figuras/resultados_ihdp/gelman_bart.pdf", units = "in" , plot = ggdraw(gelman_bart))
```

```{r}
data_autocorr_supA <- data.frame(
  dataset = rep(1:500, times = 2),
  conjunto = rep(c("Train", "Test"), each = 500),
  autocorr = c(res_sup_A$BCF.autocorr_train, res_sup_A$BCF.autocorr_test)
)

data_autocorr_supB <- data.frame(
  dataset = rep(1:500, times = 2),
  conjunto = rep(c("Train", "Test"), each = 500),
  autocorr = c(res_sup_B$BCF.autocorr_train, res_sup_B$BCF.autocorr_test)
)

data_autocorr_supA$superficie <- "sup.A"
data_autocorr_supB$superficie <- "sup.B"

data_autocorr_total <- rbind(data_autocorr_supA, data_autocorr_supB)
data_autocorr_total$grupo <- interaction(data_autocorr_total$conjunto, data_autocorr_total$superficie, sep = "_")

colores <- c(
  "Train_sup.A" = "#FFD700",    
  "Test_sup.A" = "#9370DB",     
  "Train_sup.B" = "#00C853",    
  "Test_sup.B" = "#FF4081"     
)

autocorr_bcf <- ggplot(data_autocorr_total, aes(x = autocorr, fill = grupo, color = grupo)) +
  geom_density(alpha = 0.2, linewidth = 0.8) +
  scale_fill_manual(values = colores) +
  scale_color_manual(values = colores) +
  #geom_vline(xintercept = 1.5, linetype = "solid", color = "black") +
  labs(
    #title = "Distribución de la autocorrelación por conjunto y superficie",
    x = "Autocorrelación",
    y = "Densidad",
    fill = "Grupo",
    color = "Grupo"
  ) +
  theme_minimal(base_size = 14)
autocorr_bcf
ggsave("../figuras/resultados_ihdp/autocorr_bcf.pdf", units = "in" , plot = ggdraw(autocorr_bcf))
```
```{r}
df_tiempos <- data.frame(
  tiempo = c(
    res_sup_A$BART.tiempo.s., res_sup_A$BCF.tiempo.s., res_sup_A$CF.tiempo.s.,
    res_sup_B$BART.tiempo.s., res_sup_B$BCF.tiempo.s., res_sup_B$CF.tiempo.s.
  ),
  modelo = factor(rep(c("BART", "BCF", "CF"), each = 500, times = 2)),
  superficie = rep(c("sup.A", "sup.B"), each = 3 * 500)
)

tiempos_todos <- ggplot(df_tiempos, aes(x = modelo, y = tiempo, fill = superficie)) +
  geom_boxplot(alpha = 0.7, outlier.alpha = 0.3) +
  scale_fill_manual(values = c("sup.A" = "#FFD700", "sup.B" = "#FF4081")) +
  labs(
    #title = "Distribución del tiempo de ejecución por modelo y superficie",
    x = "Modelo",
    y = "Tiempo (segundos)",
    fill = "Superficie"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = c(0.8, 0.8),
      legend.background = element_rect(
      fill = "white",    # color de fondo del recuadro
      color = "black",   # color del borde
      linewidth = 0.5    # grosor del borde
    )
  )

tiempos_todos
ggsave("../figuras/resultados_ihdp/tiempo_ejec.pdf", units = "in" , plot = ggdraw(tiempos_todos))
```


